### ISSUE TITLE
iOS handle deeplink from push notification not working

### ISSUE THREAD

**Issue by EstevaoCoelhoRobbin** [customerio/customerio-flutter#128]
Related: https://github.com/customerio/customerio-flutter/issues/35

Using a iOS device when I click in push notification, app is opened but don't navigate to deeplink. 
Using a Android device works normally.
It's an Flutter App, using customer_io: ^1.3.1 version:

All other things like push status tracking are working normally. 

here is my ios/Podfile:
```# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'CustomerIO/MessagingPushFCM', '~> 2.13' # install production build

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
     # adding to fix this issue: https://github.com/DataDog/dd-sdk-flutter/issues/480
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

target 'NotificationServiceExtension' do
  use_frameworks!
  pod 'CustomerIO/MessagingPushFCM', '~> 2.13' # install production build
end
```

my ios/AppDelegate.swift file:
```
import UIKit
import Flutter
import IDwallToolkit
import CioMessagingPushFCM
import CioTracking
import FirebaseMessaging
import FirebaseCore

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        
        // Set FCM messaging delegate
        Messaging.messaging().delegate = self
        
        // This line of code is required in order for the Customer.io SDK to handle push notification click events.
        // We are working on removing this requirement in a future release.
        // Remember to modify the siteId and apiKey with your own values.
        // let siteId = "YOUR SITE ID HERE"
        // let apiKey = "YOUR API KEY HERE"
        CustomerIO.initialize(siteId: "OMITTED", apiKey: "OMITTED", region: Region.US) { config in
            // To confirm that `delivered` push metrics are tracked, set this to true.
            config.autoTrackPushEvents = true
            config.logLevel = .debug
        }
        // Initialize Customer.io push features after you initialize the SDK:
        MessagingPushFCM.initialize { config in
            // Automatically register push device tokens to the Customer.io SDK
            config.autoFetchDeviceToken = true
            // When your app is in the foreground and a push is delivered, show the push
            config.showPushAppInForeground = true
        }
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    func application(application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().setAPNSToken(deviceToken, type: .unknown);
    }
    override func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        MessagingPush.shared.application(application, didFailToRegisterForRemoteNotificationsWithError: error)
    }
}

extension AppDelegate: MessagingDelegate {
    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        // Send the FCM token to Customer.io
        MessagingPush.shared.messaging(messaging, didReceiveRegistrationToken: fcmToken)
    }
}
```

MY pubspec.yaml file:
```
name: APP_NAME
description: APP_DESC
version: APP_VERSION

environment:
  sdk: "3.4.1"

dependencies:
  flutter:
    sdk: flutter
  {MY_MODULES}

  customer_io: ^1.3.1
  webview_flutter: 4.7.0
  firebase_crashlytics: ^3.5.5
  intl: ^0.18.0
  firebase_core: ^2.31.0
  firebase_remote_config: ^4.4.5
  firebase_messaging: ^14.9.2
  firebase_analytics: ^10.10.5

dependency_overrides:
  test_api: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  injectable_generator: 2.6.1
  flutter_lints: 2.0.2
  melos: 6.0.0
```
